//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPlaysGameboy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPlaysGameboy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgbexe {
            get {
                object obj = ResourceManager.GetObject("bgbexe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version=0
        ///WaveOut=1
        ///WavFileOut=0
        ///Outchan=0
        ///Samplerate=44100
        ///8Bits=0
        ///RecordPrefix=bgb
        ///RecordMovie=0
        ///RecordHalfSpeed=1
        ///LastRomDir=
        ///RomDir=
        ///SaveRamDir=
        ///Width=320
        ///Height=288
        ///WinX=640
        ///WinY=512
        ///PauseOnDefocus=0
        ///NoWindow=0
        ///DblClickBorderless=0
        ///Windowmode=0
        ///FullscreenMode=1
        ///Gamma=2
        ///ColorSaturation=0.85
        ///ColorWhitepoint=16777215
        ///ReflectorColor=
        ///DetectGBP=0
        ///DetectGBA=0
        ///StayOnTop=0
        ///FrameRate=0
        ///MaxSkip=3
        ///CheatAutoSave=0
        ///StateAutoConvert=1
        ///StateRomPath=0
        ///RTCLegacy=1
        ///RTCVBA=1
        ///Volume=90
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bgbini {
            get {
                return ResourceManager.GetString("bgbini", resourceCulture);
            }
        }
    }
}
